### ISSUE TITLE
Физическая схема БД

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#10]

**Comment by AnalitikBigData** [comment]
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customer"
(
    "ID_customer" integer NOT NULL DEFAULT 'nextval('"Customer_ID_customer_seq"'::regclass)',
    "Name_customer" text COLLATE pg_catalog."default" NOT NULL,
    "Number_customer" integer NOT NULL,
    "Mail_customer" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Customer" PRIMARY KEY ("ID_customer")
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "ID_employee" integer NOT NULL DEFAULT 'nextval('"Employee_ID_employee_seq"'::regclass)',
    "Surname_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Name_employee" text COLLATE pg_catalog."default" NOT NULL,
    "FatherName_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Post_employee" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    CONSTRAINT "PK_Employee" PRIMARY KEY ("ID_employee")
);

CREATE TABLE IF NOT EXISTS public."Factories"
(
    "ID_factory" integer NOT NULL DEFAULT 'nextval('"Factories_ID_factory_seq"'::regclass)',
    "Name_factory" text COLLATE pg_catalog."default" NOT NULL,
    "Specialization_factory" text COLLATE pg_catalog."default" NOT NULL,
    "Adress_factory" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Factories" PRIMARY KEY ("ID_factory")
);

CREATE TABLE IF NOT EXISTS public."Instrument"
(
    "ID_instrument" integer NOT NULL DEFAULT 'nextval('"Instrument_ID_instrument_seq"'::regclass)',
    "Name_instrument" text COLLATE pg_catalog."default" NOT NULL,
    "Materials" text COLLATE pg_catalog."default" NOT NULL,
    "WarehousesID_warehouses" integer NOT NULL,
    "Year_of_realize" integer NOT NULL,
    "Price_of_arrival" real NOT NULL,
    "Instruction" text COLLATE pg_catalog."default" NOT NULL,
    "Instrument_state" text COLLATE pg_catalog."default" NOT NULL,
    "Sale_price" real NOT NULL,
    "Warrantly_card" text COLLATE pg_catalog."default" NOT NULL,
    "Date_of_arrival" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    "FactoriesID_factory" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Instrument" PRIMARY KEY ("ID_instrument")
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    "ID_order" integer NOT NULL DEFAULT 'nextval('"Order_ID_order_seq"'::regclass)',
    "CustomersID_customer" integer NOT NULL,
    "Total_amount" real NOT NULL,
    CONSTRAINT "PK_Order" PRIMARY KEY ("ID_order")
);

CREATE TABLE IF NOT EXISTS public."Order_lines"
(
    "InstrumentsID_instrument" integer NOT NULL,
    "ServicesID_service" integer NOT NULL,
    "OrdersID_order" integer NOT NULL,
    "EmployeesID_employee" integer NOT NULL DEFAULT 0,
    CONSTRAINT "Order_lines_pkey" PRIMARY KEY ("InstrumentsID_instrument", "ServicesID_service", "EmployeesID_employee", "OrdersID_order")
);

CREATE TABLE IF NOT EXISTS public."Service"
(
    "ID_service" integer NOT NULL DEFAULT 'nextval('"Service_ID_service_seq"'::regclass)',
    "Type_service" text COLLATE pg_catalog."default" NOT NULL,
    "Service_state" text COLLATE pg_catalog."default" NOT NULL,
    "Service_price" real NOT NULL,
    date_of_aplication timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    date_of_comletion timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_Service" PRIMARY KEY ("ID_service")
);

CREATE TABLE IF NOT EXISTS public."Warehouse"
(
    "ID_warehouses" integer NOT NULL DEFAULT 'nextval('"Warehouse_ID_warehouses_seq"'::regclass)',
    "Warehouses_adress" text COLLATE pg_catalog."default" NOT NULL,
    "Capacity" integer NOT NULL,
    CONSTRAINT "PK_Warehouse" PRIMARY KEY ("ID_warehouses")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Instrument"
    ADD CONSTRAINT "FK_Instrument_Factories_FactoriesID_factory" FOREIGN KEY ("FactoriesID_factory")
    REFERENCES public."Factories" ("ID_factory") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Instrument_FactoriesID_factory"
    ON public."Instrument"("FactoriesID_factory");


ALTER TABLE IF EXISTS public."Instrument"
    ADD CONSTRAINT "FK_Instrument_Warehouse_WarehousesID_warehouses" FOREIGN KEY ("WarehousesID_warehouses")
    REFERENCES public."Warehouse" ("ID_warehouses") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Instrument_WarehousesID_warehouses"
    ON public."Instrument"("WarehousesID_warehouses");


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "FK_Order_Customer_CustomersID_customer" FOREIGN KEY ("CustomersID_customer")
    REFERENCES public."Customer" ("ID_customer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Order_CustomersID_customer"
    ON public."Order"("CustomersID_customer");


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Order_OrdersID_order" FOREIGN KEY ("OrdersID_order")
    REFERENCES public."Order" ("ID_order") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Order_lines_OrdersID_order"
    ON public."Order_lines"("OrdersID_order");


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Service_ServicesID_service" FOREIGN KEY ("ServicesID_service")
    REFERENCES public."Service" ("ID_service") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Order_lines_ServicesID_service"
    ON public."Order_lines"("ServicesID_service");

END;

P. S. такие запросы пока сформировались в БД. (произошло это автоматически) и я не поняла, почему сформировались такие конструкции "IF NOT EXISTS public."Customer"", "pg_catalog."default"", ""ID_order" integer NOT NULL DEFAULT 'nextval('"Order_ID_order_seq"'::regclass)'," MATCH SIMPLE? 
И там не все ещё атрибуты перешли пока, потому что не обновила приложение и бд

**Comment by wldmr-key** [comment]
такой вывод схемы вполне нормален, ну уже сейчас есть претензии

НИКОГДА не делай деньги и количества типом real. Либо integer, либо numeric (decimal)

Как объяснишь
ON UPDATE NO ACTION
ON DELETE CASCADE ?

**Comment by AnalitikBigData** [comment]
1) _Как объяснишь
ON UPDATE NO ACTION
ON DELETE CASCADE ?_
Ограничения целостности - в ON DELETE CASCADE удалит все связные строки; NO ACTION - если изменится строка, то в связных строках, при выполнении выпадет ошибка (ошибка не сразу , а при каких-то действиях дальше)
2) исправила типы данных

BEGIN;


CREATE TABLE IF NOT EXISTS public."Customers"
(
    "ID_customer" integer NOT NULL DEFAULT 'nextval('"Customers_ID_customer_seq"'::regclass)',
    "Name_customer" text COLLATE pg_catalog."default" NOT NULL,
    "Number_customer" integer,
    "Mail_customer" text COLLATE pg_catalog."default",
    "Login_customer" text COLLATE pg_catalog."default" NOT NULL,
    "Password_customer" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("ID_customer"),
    CONSTRAINT "UID_customer" UNIQUE ("ID_customer"),
    CONSTRAINT "ULogin_customer" UNIQUE ("Login_customer"),
    CONSTRAINT "UName_customer" UNIQUE ("Name_customer")
);

CREATE TABLE IF NOT EXISTS public."Employees"
(
    "ID_employee" integer NOT NULL DEFAULT 'nextval('"Employees_ID_employee_seq"'::regclass)',
    "Surname_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Name_employee" text COLLATE pg_catalog."default" NOT NULL,
    "FatherName_employee" text COLLATE pg_catalog."default",
    "Post_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Role_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Login_employee" text COLLATE pg_catalog."default" NOT NULL,
    "Password_employee" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("ID_employee"),
    CONSTRAINT "UID_employee" UNIQUE ("ID_employee"),
    CONSTRAINT "ULogin_employee" UNIQUE ("Login_employee")
);

CREATE TABLE IF NOT EXISTS public."Factories"
(
    "ID_factory" integer NOT NULL DEFAULT 'nextval('"Factories_ID_factory_seq"'::regclass)',
    "Name_factory" text COLLATE pg_catalog."default" NOT NULL,
    "Specialization_factory" text COLLATE pg_catalog."default" NOT NULL,
    "Adress_factory" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Factories" PRIMARY KEY ("ID_factory"),
    CONSTRAINT "UID_factory" UNIQUE ("ID_factory")
);

CREATE TABLE IF NOT EXISTS public."Instruments"
(
    "ID_instrument" integer NOT NULL DEFAULT 'nextval('"Instruments_ID_instrument_seq"'::regclass)',
    "Name_instrument" text COLLATE pg_catalog."default" NOT NULL,
    "Class_instrument" text COLLATE pg_catalog."default" NOT NULL,
    "Type_instrument" text COLLATE pg_catalog."default" NOT NULL,
    "Year_of_realize" integer,
    "Materials_instrument" text[] COLLATE pg_catalog."default",
    "FactoriesID_factory" integer,
    "WarehousesID_warehouses" integer,
    "Date_of_arrival_instrument" timestamp with time zone,
    "Price_of_arrival_instrument" numeric,
    "Instruction_instrument" text COLLATE pg_catalog."default",
    "Instrument_state" text COLLATE pg_catalog."default",
    "Sale_price_instrument" numeric,
    "Warrantly_card_instrument" text COLLATE pg_catalog."default",
    "Image_instrument" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Instruments" PRIMARY KEY ("ID_instrument"),
    CONSTRAINT "UID_instrument" UNIQUE ("ID_instrument")
);

CREATE TABLE IF NOT EXISTS public."Order_lines"
(
    "InstrumentsID_instrument" integer NOT NULL,
    "EmployeesID_employee" integer NOT NULL,
    "ServicesID_service" integer NOT NULL,
    "OrdersID_order" integer NOT NULL,
    CONSTRAINT "PK_Order_lines" PRIMARY KEY ("InstrumentsID_instrument", "EmployeesID_employee", "ServicesID_service", "OrdersID_order")
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    "ID_order" integer NOT NULL DEFAULT 'nextval('"Orders_ID_order_seq"'::regclass)',
    "Number_order" integer NOT NULL,
    "CustomersID_customer" integer NOT NULL,
    "Total_amount_order" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("ID_order"),
    CONSTRAINT "UID_order" UNIQUE ("ID_order"),
    CONSTRAINT "UNumber_order" UNIQUE ("Number_order")
);

CREATE TABLE IF NOT EXISTS public."Services"
(
    "ID_service" integer NOT NULL DEFAULT 'nextval('"Services_ID_service_seq"'::regclass)',
    "Type_service" text COLLATE pg_catalog."default" NOT NULL,
    "Service_state" text COLLATE pg_catalog."default" NOT NULL,
    "Date_of_aplication_service" timestamp with time zone NOT NULL,
    "Date_of_comletion_service" timestamp with time zone NOT NULL,
    "Time_realization_service" numeric NOT NULL,
    "Service_price" numeric NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("ID_service"),
    CONSTRAINT "UID_service" UNIQUE ("ID_service")
);

CREATE TABLE IF NOT EXISTS public."Warehouses"
(
    "ID_warehouses" integer NOT NULL DEFAULT 'nextval('"Warehouses_ID_warehouses_seq"'::regclass)',
    "Warehouses_adress" text COLLATE pg_catalog."default" NOT NULL,
    "Capacity" integer NOT NULL,
    CONSTRAINT "PK_Warehouses" PRIMARY KEY ("ID_warehouses"),
    CONSTRAINT "UID_warehouse" UNIQUE ("ID_warehouses")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Instruments"
    ADD CONSTRAINT "FK_Instruments_Factories_FactoriesID_factory" FOREIGN KEY ("FactoriesID_factory")
    REFERENCES public."Factories" ("ID_factory") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Instruments_FactoriesID_factory"
    ON public."Instruments"("FactoriesID_factory");


ALTER TABLE IF EXISTS public."Instruments"
    ADD CONSTRAINT "FK_Instruments_Warehouses_WarehousesID_warehouses" FOREIGN KEY ("WarehousesID_warehouses")
    REFERENCES public."Warehouses" ("ID_warehouses") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Instruments_WarehousesID_warehouses"
    ON public."Instruments"("WarehousesID_warehouses");


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Emoloyees_EmployeesID_employees" FOREIGN KEY ("EmployeesID_employee")
    REFERENCES public."Employees" ("ID_employee") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Instruments_InstrumentsID_instrument" FOREIGN KEY ("InstrumentsID_instrument")
    REFERENCES public."Instruments" ("ID_instrument") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Orders_OrdersID_order" FOREIGN KEY ("OrdersID_order")
    REFERENCES public."Orders" ("ID_order") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Order_lines_OrdersID_order"
    ON public."Order_lines"("OrdersID_order");


ALTER TABLE IF EXISTS public."Order_lines"
    ADD CONSTRAINT "FK_Order_lines_Services_ServicesID_service" FOREIGN KEY ("ServicesID_service")
    REFERENCES public."Services" ("ID_service") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Order_lines_ServicesID_service"
    ON public."Order_lines"("ServicesID_service");


ALTER TABLE IF EXISTS public."Orders"
    ADD CONSTRAINT "FK_Orders_Customers_CustomersID_customer" FOREIGN KEY ("CustomersID_customer")
    REFERENCES public."Customers" ("ID_customer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Orders_CustomersID_customer"
    ON public."Orders"("CustomersID_customer");

END;

3) вопрос: при изменении в самой бд типа данных или чего-нибудь ещё на программе это отражается, конфликтов не произойдёт, и видит ли программа вообще транзакции/функции/триггеры, которые внутри бд  ?

**Comment by wldmr-key** [comment]
по тексту - норм

on delete cascade трактуется как весьма опасное мероприятие - я предпочитаю его использовать только после тщательного обдумывания (даже если у меня в программе вообще нет delete - можно при администрировании/поддержке накосить)

программа никогда не видит транзакции, за исключением тех случаев, когда она сама непосредственно управляет транзакцией

программа видит функции, на которые есть права в ее роли, и может их использовать

программа в общем случае не видит триггеры, они работают сами при операциях модификации

**Comment by AnalitikBigData** [comment]
1. _on delete cascade трактуется как весьма опасное мероприятие - я предпочитаю его использовать только после тщательного обдумывания (даже если у меня в программе вообще нет delete - можно при администрировании/поддержке накосить)_ - опасный , потому что удаление и зависимый строк? А что тогда использовать RESTRICT / NO ACTION? 
2. про функции поняла

**Comment by wldmr-key** [comment]
да, я бы лучше так сделал
