### ISSUE TITLE
Приложение

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#11]

**Comment by AnalitikBigData** [comment]
вопросы 
1. вот есть сущность "строки заказа" - получается её нужно использовать для поиска? по сути менять или создавать строки заказа не нужно - они же сформируются из ID. или методы создания должны быть?
2. обычная регистрация работает, но я хотела сделать, чтобы при регистрации пароль формировался с логином автоматически (e. g. ваш логин и пароль для входа в лк такой и такой), но тк форма регистрации отправляется сразу, то не проходит в бд, тк считается что поля null. как такое реализовать лучше?

**Comment by wldmr-key** [comment]
1. строки заказа нужны для сборки заказа, которая получается как 
Order join Order lines on ID_order = OrdersID_order join ...
 - кстати, смотри какие неудобные идентификаторы для запроса
 - и, да, внушает подозрение
 
> "InstrumentsID_instrument" integer NOT NULL,
"ServicesID_service" integer NOT NULL,

неужели, у тебя в заказе не может быть только услуги или только инструмента. Скорее, в строках они должны быть взаимоисключающими

Поэтому PK на базе nullable атрибутов, хоть и является возможным в ряде СУБД (а в ряде не является) - это плохая практика

2. Не очень понял вопрос. Если при регистрации ты не даешь вводить пользователю логин/пароль, то сама вставляй их в базу вместе с полями, заполненными пользователем и ставь его перед фактом

**Comment by AnalitikBigData** [comment]
1. _кстати, смотри какие неудобные идентификаторы для запроса_  - а так с entityfraimwork получилось, пока настраивала FK. (неудобно да)
2. _и, да, внушает подозрение
"InstrumentsID_instrument" integer NOT NULL,
"ServicesID_service" integer NOT NULL,
неужели, у тебя в заказе не может быть только услуги или только инструмента._ - а как инструмент без услуги в заказе или услуга без инструмента (как я думаю, не понятно почему был в заказе просто рояль (купили - ремонтировали или еще что не несет информации)), или услуга для чего существовала в заказе. => PK не должен быть null , по идее

**Comment by wldmr-key** [comment]
купили барабан. Ну, купили и все. Или покупка - это тоже услуга? ))

**Comment by AnalitikBigData** [comment]
купили барабан. Ну, купили и все. Или покупка - это тоже услуга? )) - покупка - это услуга

**Comment by AnalitikBigData** [comment]
Вопросы

1. Хранение фотографий. Их извлекаю по ссылке с сервера. А плохо будет , если я фото расположу в облачном хранилище (в Google disk - как удаленный сервер)?
2. А вот списание на складах инструмента после покупки - это транзакция ?

**Comment by wldmr-key** [comment]
> Вопросы
> 
> 1. Хранение фотографий. Их извлекаю по ссылке с сервера. А плохо будет , если я фото расположу в облачном хранилище (в Google disk - как удаленный сервер)?

не страшно в данном случае. Правда с CORS придется ппознакомиться ))

> 2. А вот списание на складах инструмента после покупки - это транзакция ?

если это операция над БД, которая должна произойти одновременно с вставкой покупки, то бесспорно

**Comment by AnalitikBigData** [comment]
Проблема со строками заказа - 
1. в сущности 4 id (id_instrument, id_employee, id_order, id_service)  при  создании новой строки вызывать 4 формы для заполнения (1 форма по инструменту, 2 - услуга , 3 - заказ и 4 -  сотрудник) и их id уже передать в строку? 
2. и что делать с сотрудником тогда - его же выбирать нельзя если смотреть со стороны клиента, по идее?

**Comment by wldmr-key** [comment]
> Проблема со строками заказа -
> 
> 1. в сущности 4 id (id_instrument, id_employee, id_order, id_service)  при  создании новой строки вызывать 4 формы для заполнения (1 форма по инструменту, 2 - услуга , 3 - заказ и 4 -  сотрудник) и их id уже передать в строку?

не так. На клиента подкатываешь список инструментов и услуг. В форме он их выбирает из выпадающего списка (скорее всего). Если это редактируемый заказ, то его id ты знаешь, если новый - присвоишь сама на сервере при сохранении. Сотрудника, ты права, клиент не знает, поэтому, заполнение этого поля происходит в другом процессе

> 2. и что делать с сотрудником тогда - его же выбирать нельзя если смотреть со стороны клиента, по идее?

конечно

**Comment by AnalitikBigData** [comment]
составной ключ решила убрать - ввела просто id строки. 
1. _На клиента подкатываешь список инструментов и услуг. В форме он их выбирает из выпадающего списка (скорее всего)_ - с услугами да, а инструменты тоже все в список? услугу я в строку заказа добавила, сотрудника тоже. Что делать с инструментами - если покупка, то это список который есть на сайте. А последующие услуги как по инструменту отследить - по гарантийному  талону (тогда наверно, его сделать не стройкой а bool)? Потому что в другом заказе, в принципе, я не знаю точно тот или другой инструмент  (могли принести на ремонт ил другую услугу похожий, но не из этого магазина инструмент) => только гарантийный талон как-то несет информацию. 
в принципе, вот один и тоже инструмент может быть несколько раз в ремонте и настройке, и при этом его просто приносили, без покупки? получается что при сборе строки может заново создаваться инструмент в бд, а это не хорошо. не знаю на такие услуги тоже гарант талон приложить и искать по бд инструмент с такими же атрибутами , как и было в заявке => не создавать новый объект?
2. в магазине могут быть одинаковые инструменты. я пока их всех вывожу по айди, так и оставить? как я видела, одинаковые товары на странице не дублируются. тогда если я их по названию выводить буду, то как на один и тоже инструмент покупку не совершить 2 или более людям?
3. и когда собираю данные на инструмент в комиссионку, то можно принести инструмент такого завода которого нет, тогда надо его добавить, тогда это пользователю указать на сайте что есть производитель, а админ ведет список всех инструментов, изменит как надо с новым заводом?

**Comment by wldmr-key** [comment]
Это стандартная ситуация, когда ошибки при проектировании возникают в последнюю секунду реализации ))
Очень мило, что ты не задвигаешь их, а пытаешься решить

> 
> 1. _На клиента подкатываешь список инструментов и услуг. В форме он их выбирает из выпадающего списка (скорее всего)_ - с услугами да, а инструменты тоже все в список? услугу я в строку заказа добавила, сотрудника тоже. Что делать с инструментами - если покупка, то это список который есть на сайте. А последующие услуги как по инструменту отследить - по гарантийному  талону (тогда наверно, его сделать не стройкой а bool)? Потому что в другом заказе, в принципе, я не знаю точно тот или другой инструмент  (могли принести на ремонт ил другую услугу похожий, но не из этого магазина инструмент) => только гарантийный талон как-то несет информацию.

Все проще, на мой взгляд. Ты находишь инструмент по дате покупки, которую сообщает тебе клиент (если это ремонт) и решаешь гарантия/не гарантия. Обращаю внимание, мы с тобой обсуждали вопрос об уникальной идентификации каждого инструмента ))

>    в принципе, вот один и тоже инструмент может быть несколько раз в ремонте и настройке, и при этом его просто приносили, без покупки? получается что при сборе строки может заново создаваться инструмент в бд, а это не хорошо. не знаю на такие услуги тоже гарант талон приложить и искать по бд инструмент с такими же атрибутами , как и было в заявке => не создавать новый объект?

еще раз - ты ищешь не среди всех иснтрументов, а среди покупок указанного клиента

> 2. в магазине могут быть одинаковые инструменты. я пока их всех вывожу по айди, так и оставить? как я видела, одинаковые товары на странице не дублируются. тогда если я их по названию выводить буду, то как на один и тоже инструмент покупку не совершить 2 или более людям?

при показе ты не дублируешь id, при покупке - заносишь уникальный id. Не вижу проблемы

> 3. и когда собираю данные на инструмент в комиссионку, то можно принести инструмент такого завода которого нет, тогда надо его добавить, тогда это пользователю указать на сайте что есть производитель, а админ ведет список всех инструментов, изменит как надо с новым заводом?

да
