### ISSUE TITLE
РПЗ

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#12]

**Comment by AnalitikBigData** [comment]
1. ссылка на файл рпз
https://drive.google.com/file/d/1PGF34m9R7Ua7zaaOn_Q1u2RwY12Um-57/view?usp=sharing

**Comment by wldmr-key** [comment]
Все отлично, но
я бы советовал вынести из п.3.1 схему в приложение к РПЗ. Оставить только перечень таблиц и слова, описывающие связи. Ну и название пункта не соответствует содержанию - ты описываешь схему БД, а не структуру приложения

3.3 - логическая схема появляется раньше физической. Не логично

А чего скриншотиков для описания интерфейсов пожалела?

**Comment by AnalitikBigData** [comment]
https://drive.google.com/file/d/1zjT6g-n1Rl0K6FbIBOhJl2B3OPcMeA1w/view?usp=sharing
перенесла в приложения, изменила расположение пунктов + оформление.
