### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#2]
Общие положения 
	1. 1. Предмет разработки
Предметом разработки является Интернет-сайт музыкального магазина, с системой динамического управления наполнением на базе веб-интерфейса. 
2. Назначение и цели создания (развития) системы 
	2. 1. Назначение системы
Назначение сайта: предоставления информации о товарах и услугах магазина, получение информации о клиентах и сотрудниках. 
	2. 2. Цель создания (развития) системы
	Система создаётся для обеспечения доступности для населения музыкальных инструментов и ускорения получения услуг (поиск услуг и просмотр товаров), предназначенных для инструментов, поиска инструментов. 
	3. Характеристика объектов автоматизации
Процесс учет заказов клиентов характеризуется  регистрацией заказа (при оформлении заказа клиент предоставляет информацию о товарах, которые он хочет приобрести), наличием товара (система должна указывать количество доступных экземпляров. Если товар отсутствует, клиент может поставить его на "ожидание" или сделать предзаказ, чтобы получить его, когда он будет в наличии), а также оплатой и доставкой (отслеживание платежей и информации о доставке. Покупатель должен иметь возможность выбрать способ оплаты (например, карта, наличные или онлайн-платежная система) и адрес доставки.  
Учет инструментов характеризуется регистрацией инструментов: при поступлении новых инструментов музыкальный магазин должен зарегистрировать каждый инструмент в системе учета. Это включает основные характеристики инструмента, такие как название, год выпуска, материал, производитель, адрес производителя, дата прихода, цена прихода, склад, инструкция, состояние, цена, гарантийный талон. Другой характеристикой является категоризация и классификация: Исходя из разнообразия музыкальных инструментов, важно иметь удобную систему категоризации и классификации. Например, инструменты можно разделить по типу (струнные, духовые, клавишные и т. д.) и по категориям внутри каждого типа. Отслеживание местонахождения: где находятся инструменты в момент учёта. Для магазинов музыкальных инструментов это может быть склад или сам магазин. Обслуживание и ремонт: получение информации о дате последнего обслуживания или ремонта. Это может помочь контролировать состояние инструментов, планировать предупредительное обслуживание и улучшить их долговечность. Для каждого инструмента можно сохранить историю обслуживания, включая даты и выполненные работы.
Ведение списка клиентов характеризуется регистрация клиентов: Первый шаг ведения списка клиентов — это регистрация информации о каждом клиенте музыкального магазина. Эта информация может включать ФИО или название организации, контактные данные (такие как телефон и электронная почта). Регистрация клиентов может осуществляться при первом контакте (например, при покупке товара) или через специальную онлайн-регистрацию. Обновление информации: список клиентов должен регулярно обновляться и дополняться новой информацией. Также важна такая характеристика как история обращений: ведение списка клиентов должно включать историю обращений с каждым клиентом. Это может включать информацию о предыдущих покупках, обращениях к службе поддержки или любых других взаимодействиях 
Ведение списка производителей характеризуется регистрация производителей: список производителей музыкальных инструментов начинается с регистрации каждого производителя в вашей базе данных. Важно хранить информацию, такую как название, адрес и специализация. Классификация производителей: Список производителей может быть организован по различным категориям и классификациям (производители струнных инструментов, ударных и другие). Контроль поставок и статусов заказов: обновление информации о поставке новых инструментов. 
Ведение списка сотрудников - Регистрация сотрудников: Это включает информацию, такую как фамилия, имя, отчество сотрудника, а также должность. Также должен быть применен поиск сотрудников (например, для поиска по определенному заказу). 
4. Требования к системе
	4. 1. Требования к системе в целом
		4. 1. 1. Требования к структуре и функционированию системы
Система подразделяется на серверную и клиентскую части. 
Со стороны серверной части: 1) регистрация в системе производителя; 2) регистрация в системе клиента; 3) регистрация заказов клиентов; 4) регистрация в системе сотрудников; 5) ведения учёта инструментов; 6) ведения учета услуг; 7) удаление клиентов; 8) изменение данных клиентов; 9) изменение информации инструментов; 10) изменение данных производителей. 
Со стороны клиентской части: 1) найти услугу; 2) найти инструмент и просмотреть информацию о нём (название, год выпуска, производитель, состояние (новый / б/у), цена, материал, фото); 3) просмотреть историю заказов; 4) заказать услугу; 5) зарегестрироваться; 6) заказать инструмент
		4. 1. 2. Требования к защите информации от несанкционированного доступа. 
		1) Требование по наличию пароля для пользователей, особенно для пользователей с ролью администратора.
		2) Реализация ролевой модели доступа.
	4. 2. Требования к функциям (задачам), выполняемым системой
		1) Подсистема Заводы - Магазин
			1. Функция добавления нового производителя. 
				Вход осуществляется администратором магазина через личный кабинет. Потом вносятся новые данные о заводе. 
			2. Изменение данных завода. Вход осуществляется администратором магазина через личный кабинет. Осуществляется поиск нужного завода и изменяется информация. 
			3. Удаление завода. Вход осуществляется администратором магазина через личный кабинет. Ищется нужный завод и удаляется. 
			4. Учёт инструментов. Вход осуществляется администратором магазина через личный кабинет. Далее распределяются инструменты по классификации. 
		2) Подсистема Магазин - Инструменты 
			1. Добавление инструмента. Вход осуществляется администратором магазина через личный кабинет. Далее он вносит инструмент  в список. 
			2. Изменение информации об инструменте. 
			3. Отслеживание наличия инструмента. После совершения заказа, товар должен списаться с сайта. И после прихода с завода добавление по количеству.  
			4. Удаление инструмента. После покупки товара инструмент удаляется по ID. 
			5. Поиск инструмента. После выбора определенных категорий или указания названия выдаётся список инструментов. 
		3) Подсистема Услуги - Магазин 
			1. Добавление услуги
			2. Изменение информации об услуги
			3. Удаление услуги
		4) Подсистема Сотрудники - Магазин 
			1. Добавление сотрудника
			2. Изменение информации о сотруднике
			3. Поиск сотрудника. Из ранее сделанных заказов можно получить информацию о сотруднике. 
			4. Удаление сотрудника. 
			5. Установление сотрудника на заказ. Если сотрудник не занят в это время на другом заказе и работает в данный момент, то переводится на обслуживание заказа. 
			6. Вход сотрудника в личный кабинет. Каждый сотрудник может входить в свой личный кабинет под своим логином и паролем, также есть роль, которая регулирует действия сотрудника (администратор имеет право получить любую информацию, вносить изменения и удалять; остальные сотрудники могут просматривать только свою статистику обслуживания). 
		5) Подсистема Заказы - Магазин
			1. Регистрация нового заказа 
			2. Получение информации о заказе
			3. Изменение заказа. Услуги и количество нужных инструментов формирует пользователь. Статус (выполнен / исполняется / отменен) заказа управляется сотрудниками, которые регулируют заказ. 
			4. Оплата заказа. После регистрации нового заказа (т. е. оформления) есть возможность его оплатить, будут предоставлены способы оплаты.
		6) Подсистема Клиенты - Магазин 
			1. Вход в личный кабинет. Осуществляется через логин и пароль. Также при входе в личный кабинет учитывается вход для физических лиц и для организаций, для этого надо выбрать изначально для заказа. 
			2. Получение информации о заказах
			3. Просмотр информации на сайте. Просмотр услуг и инструментов. 
			4. Оформление заказа
			5. Удаление личного кабинета. После этого удаляется вся информация о ранее сделанных  заказах, а также остальная информация о пользователе. 
	4. 3. Требования к видам обеспечения
		4. 3. 1. Требования к программному обеспечению системы
			Для работы с СУБД используется PostgreSQL, также необходим браузер (Chrome). 
		4. 3. 2. Требования к метематическому обеспечению системы
			Необходимо вести математичекие расчёты для суммы заказа. 
		4. 3. 3. Требования к лингвистическому обеспечению системы
			Язык интерфейса для пользователя - русский. (Название могут быть на другом языке, если так указано у производителя)
5. Состав и содержание работ по созданию системы. 
	1. Утверждение темы, задания на разработку, технического задания (альфа) (2 неделя)
	2.  Оформление ТЗ, описание предметной области и  требований к системе, аналоги, концептуальная схема, прототип или скетчи интерфейса (4 неделя)
	3.  Оформление введения и исследовательской части, 	обоснование выбора БД (если необходимо), логическая схема БД, физическая схема данных, 	демонстрация работы макета системы с БД (7 неделя)
	4.  Оформление проектно-конструкторской части, демонстрация работающего приложения, презентация (альфа), тестирование и отладка приложения, разработка эксплуатационной документации (10 неделя)
	5. Завершение работы на приложением, все ошибки и проблемы устранены, защита (14 неделя)
6. Порядок контроля и приемки системы 
7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие 
8. Требования к документированию 
Техническое задание разрабатывалось в соответствии с ГОСТ 34.602 - 89
9. Источники разработки

**Comment by AnalitikBigData** [comment]
Общие положения 
	1. 1. Предмет разработки
Предметом разработки является Интернет-сайт музыкального магазина, с системой динамического управления наполнением на базе веб-интерфейса. 
2. Назначение и цели создания (развития) системы 
	2. 1. Назначение системы
Назначение сайта: предоставления информации о товарах и услугах магазина, получение информации клиентах и сотрудниках. 
	2. 2. Цель создания (развития) системы
	Система создаётся для обеспечения доступности для населения музыкальных инструментов и получения услуг, предназначенных для инструментов. 
	3. Характеристика объектов автоматизации
Процесс учет заказов клиентов характеризуется  регистрацией заказа (при оформлении заказа клиент предоставляет информацию о товарах, которые он хочет приобрести), наличием товара (система должна указывать количество доступных экземпляров. Если товар отсутствует, клиент может поставить его на "ожидание" или сделать предзаказ, чтобы получить его, когда он будет в наличии), а также оплатой и доставкой (отслеживание платежей и информации о доставке. Покупатель должен иметь возможность выбрать способ оплаты (например, карта, наличные или онлайн-платежная система) и адрес доставки.  
Учет инструментов характеризуется регистрацией инструментов: при поступлении новых инструментов музыкальный магазин должен зарегистрировать каждый инструмент в системе учета. Это включает основные характеристики инструмента, такие как название, год выпуска, материал, производитель, адрес производителя, дата прихода, цена прихода, склад, инструкция, состояние, цена, гарантийный талон. Другой характеристикой является категоризация и классификация: Исходя из разнообразия музыкальных инструментов, важно иметь удобную систему категоризации и классификации. Например, инструменты можно разделить по типу (струнные, духовые, клавишные и т. д.) и по категориям внутри каждого типа. Отслеживание местонахождения: где находятся инструменты в момент учёта. Для магазинов музыкальных инструментов это может быть склад или сам магазин. Обслуживание и ремонт: получение информации о дате последнего обслуживания или ремонта. Это может помочь контролировать состояние инструментов, планировать предупредительное обслуживание и улучшить их долговечность. Для каждого инструмента можно сохранить историю обслуживания, включая даты и выполненные работы.
Ведение списка клиентов характеризуется регистрация клиентов: Первый шаг ведения списка клиентов — это регистрация информации о каждом клиенте музыкального магазина. Эта информация может включать ФИО или название организации, контактные данные (такие как телефон и электронная почта). Регистрация клиентов может осуществляться при первом контакте (например, при покупке товара) или через специальную онлайн-регистрацию. Обновление информации: список клиентов должен регулярно обновляться и дополняться новой информацией. Также важна такая характеристика как история обращений: ведение списка клиентов должно включать историю обращений с каждым клиентом. Это может включать информацию о предыдущих покупках, обращениях к службе поддержки или любых других взаимодействиях 
Ведение списка производителей характеризуется регистрация производителей: список производителей музыкальных инструментов начинается с регистрации каждого производителя в вашей базе данных. Важно хранить информацию, такую как название, адрес и специализация. Классификация производителей: Список производителей может быть организован по различным категориям и классификациям (производители струнных инструментов, ударных и другие). Контроль поставок и статусов заказов: обновление информации о поставке новых инструментов. 
Ведение списка сотрудников - Регистрация сотрудников: Это включает информацию, такую как фамилия, имя, отчество сотрудника, а также должность. Также должен быть применен поиск сотрудников (например, для поиска по определенному заказу). 
4. Требования к системе

**Comment by wldmr-key** [comment]
> азначение сайта: предоставления информации

для кого??!!

> Характеристика объектов автоматизации

на мой взгляд - перебор. Здесь не нужны эмоциональные характеристики ("Также важна такая характеристика") и условные наклонения ("Это может помочь контролировать"). ТЗ - это задание

Все это тебе пригодится в РПЗ, а здесь я бы сократил в 5 раз и оставил только объекты

> Со стороны серверной части: 

ты, похоже, путаешь сервер и бэкофис (магазин)

> особенно для пользователей с ролью администратора.

))

> Требования к функциям (задачам), выполняемым системой

imho - слишком детально. Не связываешь ли ты себе руки?

например

> 3. Удаление завода.

это можно делать безнаказанно?

Вообще советую подумать, не слишком ли ты разухабисто планируешь удаление?

**Comment by AnalitikBigData** [comment]
1. Назначение сайта: предоставления информации
**_для кого??!!_** 
Назначение сайта: предоставления информации населению о товарах и услугах магазина, получение информации о клиентах и сотрудниках. 
Как сказать, это же не очень большой круг лиц, либо любители или профессионалы , либо  спец организации (муз школы, театры итд). Не знаю как их обобщить , кроме слова население. 
___________
2. Характеристика объектов автоматизации
_**на мой взгляд - перебор. Здесь не нужны эмоциональные характеристики ("Также важна такая характеристика") и условные наклонения ("Это может помочь контролировать"). ТЗ - это задание

Все это тебе пригодится в РПЗ, а здесь я бы сократил в 5 раз и оставил только объекты**_

тогда получится так: Характеристика объектов автоматизации:
1. учет заказов клиентов, 
2. Учет инструментов, 
3. Ведение списка клиентов, 
4. Ведение списка производителей. 
________________
3. Со стороны серверной части:
**_ты, похоже, путаешь сервер и бэкофис (магазин)_**

Да ((( Думала, что это одно и тоже. Потом прочитала. 

напишу что приложение состоит из бэк-части и фронт-части. 
_________________
4. особенно для пользователей с ролью администратора.
))

Что-то не так? Лишнее? 
_________________
5. Про удаление **_это можно делать безнаказанно?_**

**_Вообще советую подумать, не слишком ли ты разухабисто планируешь удаление?_**
Наверно, да. Заводы и сотрудников не стоит удалять, иначе там ограничения целостности нарушатся по внешним ключам (но предусматривать, я так думаю, надо ограничения целостности).  
Удаление оставлю только для  клиентов (хотя от сущности Клиент  тоже зависимая часть в заказе).

**Comment by wldmr-key** [comment]
> Как сказать, это же не очень большой круг лиц

вполне нормально

> тогда получится так

норм, но я  бы формулировал так - объектами автоматизации являются следующие процессы работы магазина: информирование клиентов о продукции, сбор и обработка заказов, учет движения инструментов.... - дальше сама ))

> Что-то не так? Лишнее?

ну да, нельзя быть беременной наполовину. "Требование по наличию пароля" не допускает компромиссов

**Comment by AnalitikBigData** [comment]
исправленные пункты ТЗ:
2. Назначение и цели создания (развития) системы
2. 1. Назначение системы
Назначение сайта: предоставления информации населению, интересующемуся музыкой, о товарах и услугах магазина, получение информации о клиентах и сотрудниках.
2. 2. Цель создания (развития) системы
Система создаётся для обеспечения доступности для населения музыкальных инструментов и ускорения получения услуг (поиск услуг и просмотр товаров), предназначенных для инструментов, поиска инструментов.
3. Характеристика объектов автоматизации
Объектами автоматизации являются следующие процессы работы магазина:
        1. информирование клиентов о продукции
        2. сбор и обработка заказов
        3. учёт движения инструментов 
        4. регистрация и ведения списка клиентов
        5. регистрация и ведения списка производителей
        6. предоставление информации об услугах
4. Требования к системе
4. 1. Требования к системе в целом
4. 1. 1. Требования к структуре и функционированию системы
Система подразделяется на backend и frontend части.
4. 1. 2. Требования к защите информации от несанкционированного доступа.
1) Требование по наличию пароля для пользователей
2) Реализация ролевой модели доступа.
1) Подсистема Заводы - Магазин
4. 2. Требования к функциям (задачам), выполняемым системой
(исключены функции удаления для всех сущностей). 
______
будут функции: добавления (всех сущностей), изменения (всех сущностей), просмотра (товары, услуги для пользователей), отслеживание информации о товаре, поиск (услуг и товаров), установление на заказ сотрудника, личный кабинет для сотрудников, оплата заказа, вход в личный кабинет для клиентов.

**Comment by wldmr-key** [comment]
норм, хватит улучшать ))

**Comment by AnalitikBigData** [comment]
оставлять так? 
тогда останутся пункты 6. Порядок контроля и приемки системы
7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
8. Требования к документированию
Техническое задание разрабатывалось в соответствии с ГОСТ 34.602 - 89
9. Источники разработки
их попозже допишу

**Comment by wldmr-key** [comment]
ок

**Comment by AnalitikBigData** [comment]
Дописала последние пункты:
6. Порядок контроля и приемки системы
Система разрабатывется с Применением тестирования работоспообности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Приём работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры иУК5
7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
1) приведение поступающей в систему информации (в соответствии с требованиями) к виду, пригодному для обработки
2) создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ;
3) организация доступа к базам данных;
8. Техническое задание разрабатывалось в соответствии с ГОСТ 34.602 - 89
9. Источники разработки. 
Настоящее Техническое Задание разработано на основе следующих документов и информационных материалов: ГОСТ 34.602-89

**Comment by wldmr-key** [comment]
нормально, молодец
