### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#3]
Описание: 
На сайте музыкального магазина можно купить музыкальные инструменты (скрипки, фортепиано, флейты, барабаны итд). В магазине инструменты делятся на отсеки с классами (струнные, духовые, ударные итд). Инструменты сделаны на заводах, которые поставляют их в сеть магазинов. (Сотрудничество сети музыкальных магазинов с заводами по производству  музыкальных инструментов. Инструменты доставляются с помощью доставки (каким образом доставляется и кем находится вне системы, важно кто сделал инструмент)) Само по себе помещение магазина может  вмещать в себя примерно 100 - 150 товаров. У покупателя есть возможность просматривать товары в наличии онлайн. Характеристики (год выпуска, материал, инструкция) также входят к музыкальным инструментам, с которыми можно ознакомиться  онлайн  - на сайте, кликнув на товар. При покупки на сайте есть возможность заказа с доставкой или самовывоз, также возможно несколько способов оплаты: наличными при получении, картой онлайн, картой при получении.(банки и другие посредники для оплаты не важны - не входит в систему)Инструменты проверяются на наличия. 
Склад подразделяется на отсеки с разными условиями хранения музыкальных инструментов. Склад вмещает в себя около 1000 - 1500 разных музыкальных инструментов. 
В магазине есть услуги: покупки инструмента , настройки , ремонта и комиссионки. Условия покупки: выбирается инструмент, добавляется в корзину. Оформляется заказ, выбирается способ оплаты, заказ выполняется, инструмент готов к выдачи. Условия настройки: если покупка инструмента изначально, то к нему можно выбрать услугу настройки (вносится сразу в это же заказ к покупке). Также можно обратиться со своим инструментом для настройки. Тогда оформляется новый заказ для клиента, регестрируется. После осуществлении услуги производится оплата. (цена зависит от сложности настройки. Обычно формула такая: **_стоимость настройки_ = 500 + t * 10, где t - время затраченное на настройку в минутах** ) Условия ремонта: выбирается услуга ремонта к инструменту, потом осуществляется ремонт сотрудником ( стоимость ремонта = 1000 + t * 100, t - время в минутах, затраченное на ремонт), оплачивается. (ремонт производится вне системы, просто вносятся данные, что был ремонт для инструмент от клиента). Условия комиссионки: инструмент находится в хорошем состоянии и есть характеристики его, тогда можно сдавать, если цена не устроила клиента (услуга не производится), все устроило - происходит сделка. (об оказании данной услуги вносятся данные в заказе на клиента). Формирование цены: Цена инструмента = 0,85 * цена этого инструмента (по текущему курсу) + 500 Если инструмент продан, то комиссионный взнос составляет 10% от цены проданного инструмента, остальное перечисляется человеку.
Сотрудники. У каждого сотрудника есть свой личный кабинет (логин и пароль). Сотрудники распределены по ролям. Администратору разрешено вносить изменения, создавать новые объекты. Остальные сотрудники могут смотреть свою статистику работы и добавлять новые объекты. 
Клинты имеют свой личный кабинет. При входе в личный кабинет  могут сделать заказ (инструмента / услуги), просматривать товары и добавлять их в корзину. входят по логину и паролю. изменять данные о себе могут (только имя /фамилия , телефон, почта. логин и пароль изменять нельзя). 
Инструменты характеризуются названием, годом выпуска, материалом, производителем, датой прихода, ценой прихода, инструкцией, состоянием (новое с завода или б/у), ценой, расположением (находится в магазине или на складе), гарантийным талоном. Заводы характеризуются названием, специализацией и адресом. Сотрудники - Фамилия Имя Отчество , должность, логин, пароль. Склады: вместительность, местонахождение. Услуги характеризуются: тип услуги, состояние (оказана - отказано в услуге - в процессе), дата обращения и дата выполнения , цена. Кассовый чек (выдается при покупке или после выполнения ремонта/ настройки), гарантийный талон (документ, в котором установлены сроки бесплатного обслуживания - либо ремонта либо замены). Клиенты характеризуются: ФИО / название организации, номер телефона, электронная почта, логин, пароль.

**Comment by AnalitikBigData** [comment]
Требования к системе (описание см выше)
4. 1. Требования к системе в целом
4. 1. 1. Требования к структуре и функционированию системы
Система подразделяется на backend и frontend части.
Со стороны back части: 1) регистрация в системе производителя; 2) регистрация в системе клиента; 3) регистрация заказов клиентов; 4) регистрация в системе сотрудников; 5) ведения учёта инструментов; 6) ведения учета услуг; 7) удаление клиентов; 8) изменение данных клиентов; 9) изменение информации инструментов; 10) изменение данных производителей.
Со стороны frontend части: 1) найти услугу; 2) найти инструмент и просмотреть информацию о нём (название, год выпуска, производитель, состояние (новый / б/у), цена, материал, фото); 3) просмотреть историю заказов; 4) заказать услугу; 5) зарегестрироваться; 6) заказать инструмент
4. 1. 2. Требования к защите информации от несанкционированного доступа.
1) Требование по наличию пароля для пользователей
2) Реализация ролевой модели доступа.
4. 2. Требования к функциям (задачам), выполняемым системой
1) Подсистема Заводы - Магазин
1. Функция добавления нового производителя.
Вход осуществляется администратором магазина через личный кабинет. Потом вносятся новые данные о заводе.
2. Изменение данных завода. Вход осуществляется администратором магазина через личный кабинет. Осуществляется поиск нужного завода и изменяется информация.
4. Учёт инструментов. Вход осуществляется администратором магазина через личный кабинет. Далее распределяются инструменты по классификации.
2) Подсистема Магазин - Инструменты
1. Добавление инструмента. Вход осуществляется администратором магазина через личный кабинет. Далее он вносит инструмент в список.
2. Изменение информации об инструменте.
3. Отслеживание наличия инструмента. После совершения заказа, товар должен списаться с сайта. И после прихода с завода добавление по количеству.
5. Поиск инструмента. После выбора определенных категорий или указания названия выдаётся список инструментов.
3) Подсистема Услуги - Магазин
1. Добавление услуги
2. Изменение информации об услуги
4) Подсистема Сотрудники - Магазин
1. Добавление сотрудника
2. Изменение информации о сотруднике
3. Поиск сотрудника. Из ранее сделанных заказов можно получить информацию о сотруднике.
5. Установление сотрудника на заказ. Если сотрудник не занят в это время на другом заказе и работает в данный момент, то переводится на обслуживание заказа.
6. Вход сотрудника в личный кабинет. Каждый сотрудник может входить в свой личный кабинет под своим логином и паролем, также есть роль, которая регулирует действия сотрудника (администратор имеет право получить любую информацию, вносить изменения и удалять; остальные сотрудники могут просматривать только свою статистику обслуживания).
5) Подсистема Заказы - Магазин
1. Регистрация нового заказа
2. Получение информации о заказе
3. Изменение заказа. Услуги и количество нужных инструментов формирует пользователь. Статус (выполнен / исполняется / отменен) заказа управляется сотрудниками, которые регулируют заказ.
4. Оплата заказа. После регистрации нового заказа (т. е. оформления) есть возможность его оплатить, будут предоставлены способы оплаты.
6) Подсистема Клиенты - Магазин
1. Вход в личный кабинет. Осуществляется через логин и пароль. Также при входе в личный кабинет учитывается вход для физических лиц и для организаций, для этого надо выбрать изначально для заказа.
2. Получение информации о заказах
3. Просмотр информации на сайте. Просмотр услуг и инструментов.
4. Оформление заказа
4. 3. Требования к видам обеспечения
4. 3. 1. Требования к программному обеспечению системы
Для работы с СУБД используется PostgreSQL, также необходим браузер (Chrome).
4. 3. 2. Требования к метематическому обеспечению системы
Необходимо вести математичекие расчёты для суммы заказа.
4. 3. 3. Требования к лингвистическому обеспечению системы
Язык интерфейса для пользователя - русский. (Название могут быть на другом языке, если так указано у производителя)

**Comment by wldmr-key** [comment]
В требованиях не имеет больщого смысла повторять требования ТЗ (это само собой разумеется. С другой стороны и вреда особого тоже нет) - гораздо больше внимания следует обратить на сущностный и атрибутный состав. С сущностями и, пожалуй, связями у тебя все ок (во всяком случае, я плюшек не нашел), а однозначного описания всех атрибутов в нужных местах нет

Примеры - "Изменение информации о сотруднике" - какой? Кем?
"Получение информации о заказах" - какой?

и так далее

В описании у тебя есть формулы для услуг и ремонта типа стоимость настройки = 500 + t * 10. Я надеюсь, что 500 и 10 будут конфигурируемыми параметрами (инфляция), а t будет кем-то вноситься (не увидел, кем и где, может, плохо смотрел)

**Comment by AnalitikBigData** [comment]
исправление описания и требований
Описание:  
В музыкальном магазине можно купить музыкальные инструменты (скрипки, фортепиано, флейты, барабаны итд). В магазине инструменты делятся на отсеки с классами (струнные, духовые, ударные итд). Инструменты сделаны на заводах, которые поставляют их в магазин. (Сотрудничество музыкального магазина с заводами по производству музыкальных инструментов.
Каждый завод имеет специализацию производства, т.е. изготавливает инструменты определённого класса. Потом доставляет инструменты в магазины. (Доставка (кто и как доставляет) осуществляется с адреса производителя вне системы разрабатываемой системы). 
Инструменты поступают по цене прихода. Также у каждого инструмента есть время прихода в магазин.  
Само по себе помещение магазина может вмещать в себя примерно 100 - 150 товаров. При покупке можно узнать информацию о товаре. Каждый товар имеет характеристики : название, год выпуска, материал, производитель, инструкция, состояние (новое или б/у), расположение (на складе или магазин), цену продажи. После совершения покупки на товар выдаётся чек. При покупке есть возможность заказа с доставкой или самовывоз.  
В магазине, кроме покупки инструмента, доставки, в магазине есть услуги ремонта, настройки и комиссионные услуги. Настройка - ввести инструмент до рабочего состояния, т. е. инструмент не сломан , а просто для его работы нужны небольшие изменения для использования. Цена настройки   = 500 + t * 10, где t - время затраченное на настройку в минутах. Время обслуживания вносит сотрудник, оказывающий услугу.  Ремонт  применяется, когда инструмент не исправен. Цена ремонта = 1000 + t * 100, t - время в минутах, затраченное на ремонт, записывает сотрудник. Условия комиссионной услуги: инструмент может быть принят в магазин при нескольких условиях: 1) инструмент исправен 2) у клиента есть данные о производителе, годе выпуска, материал, инструкция. Далее предлагается клиенту цена, по которой будет продаваться инструмент. Если клиента всё устроило, то инструмент приходит на продажу. Принимать б/у инструмент может один сотрудник, а продать другой. Если инструмент купили, то  цена инструмента = 0,8 * цена этого инструмента (примерно из оценки таких же инструментов - назначит оценщик) + 500. Комиссионный взнос составляет 20% от цены проданного инструмента, остальное перечисляется человеку. Любая услуга имеет дату обращения и дату выполнения, а также состояние (выполнена, в обработке, отказано).  
Склад подразделяется на отсеки с разными условиями хранения музыкальных инструментов. Склад вмещает в себя около 1000 - 1500 разных музыкальных инструментов. Склад находится по определённому адресу.  Сотрудники выполняют разные функции. Для этого разделены по должностям. У каждого сотрудника есть свой личный кабинет (логин и пароль). Сотрудники распределены по ролям. Администратору разрешено вносить изменения, создавать новые объекты. Остальные сотрудники могут смотреть свою статистику работы и добавлять новые объекты. Клиенты имеют свой личный кабинет. При входе в личный кабинет могут сделать заказ (инструмента / услуги), просматривать товары и добавлять их в корзину. Вход осуществляется по логину и паролю. изменять данные о себе могут (только имя /фамилия , телефон, почта. Логин и пароль изменять нельзя).
Клиенты могут делать заказы, для клиента формируется номер заказа, в котором будут услуги, инструменты, а также сотрудники , которые участвовали в исполнении заказа. При новом обращении клиента формируется новый заказ. В конце заказа будет общая сумма.  
Требования к системе:
1. У каждого сотрудника есть свой личный кабинет. При выполнении определенных функций (изменении информации, добавлении) необходим администратор. 
2. Логин и пароль клиентов и сотрудников должны различаться. 
3. Инструменты должны быть распределены по классам для поиска
4. Отслеживать наличие инструмента
5. Установление сотрудника на заказ. Если сотрудник не занят в это время на другом заказе и работает в данный момент, то переводится на обслуживание заказа.
6. У клиентов должна быть функция изменения своего профиля (Имя, телефон, почта), кроме логина и пароля. 
7. Логин и пароль формирует система при регистрации, их изменять нельзя
8. Должна быть ролевая модель в системе

P. S. есть вопросы 
1) что делать с инструментом , который купили, не удалять же, ввести атрибут куплен (bool) - true/false? 
2) немного запуталась, цена - это атрибут инструмента ? продажа - это точно услуга, значит у нее должна быть цена -> есть такой заказ -  
            1. Продажа скрипки 5000 
            2. Ремонт саксофона 1000      (саксофон не обязательно куплен в этом магазине) => 5000 и 3000 это цены услуг. Тогда у инструмента в ремонте нет цены, тк важен ремонт. Как это? 
3) тогда из предыдущего пункта вся система начинает ломаться из-за инструментов из вне, которые не проходили никогда в магазин.  Как тогда собрать информацию об инструменте (кто производитель, название точное ) при записи на услугу?

**Comment by wldmr-key** [comment]
> 
> P. S. есть вопросы
> 
> 1. что делать с инструментом , который купили, не удалять же, ввести атрибут куплен (bool) - true/false?

убрать его со склада, не?

> 2. немного запуталась, цена - это атрибут инструмента ? продажа - это точно услуга, значит у нее должна быть цена -> есть такой заказ -

продажа - это, безусловно, услуга, но в магазине ее цена включена в цену товара.

>    1. Продажа скрипки 5000
>    2. Ремонт саксофона 1000      (саксофон не обязательно куплен в этом магазине) => 5000 и 3000 это цены услуг. Тогда у инструмента в ремонте нет цены, тк важен ремонт. Как это?

речь идет о саксофоне? Если тебе важна история его ремонтов, то заполняешь его карточку, цена, ты права, абсолютно неважна, как и многие другие атрибуты. Если тебе история ремонтов конкретного инструмента по барабану, то в строке заказа стоит ремонт левого саксофона и никаких заморочек. Первый вариант мне кажется более правильным

> 3. тогда из предыдущего пункта вся система начинает ломаться из-за инструментов из вне, которые не проходили никогда в магазин.  Как тогда собрать информацию об инструменте (кто производитель, название точное ) при записи на услугу?

С какой целью интересуетесь? ))
зачем тебе эта информация? Все как в жизни - что знаешь, то фиксируешь. На мой взгляд, ничего не сломается

**Comment by AnalitikBigData** [comment]
1. убрать его со склада, не? - наверно, да
2. речь идет о саксофоне? Если тебе важна история его ремонтов, то заполняешь его карточку, цена, ты права, абсолютно неважна, как и многие другие атрибуты. - попробую так сделать.

**Comment by AnalitikBigData** [comment]
Моё предположение о хранении несчастных коэффициентах и параметрах. 
Цена настройки = 500 + t * 10, где t - время затраченное на настройку в минутах. Цена ремонта = 1000 + t * 100, t - время в минутах, затраченное на ремонт, записывает сотрудник. 0,8 * цена этого инструмента (примерно из оценки таких же инструментов - назначит оценщик) + 500.
Несколько идей:
1. Прописать как новые атрибуты в сущности Услуги (коэф, время обслуживания). Хотя время обслуживания  надо включить как атрибут наверно (время завершения - время обращения не одно и тоже время обслуживания. ). А дальше через функцию прописать вычисление , где вычистился значение цены. 
2. либо не включать в сущность атрибут "коэф", а сразу прописать функцию PostgerSql с возвращением цены, а когда произойдут изменения (инфляция или новая ценовая политика), тогда изменить функцию админу. Как мне кажется, делать как атрибут коэф не стоит.

**Comment by wldmr-key** [comment]
и то, и другое не выглядят промышленными решениями (хотя я знаю нескольких профи, которые сделали бы такую сущность. Впрочем, они и мужской-женский пол сделали бы справочником (вдруг, в будущем это поменяется)

Как правило, такие вещи прописываются в месте, именуемом конфигурацией или конфигурационным файлом. Туда прописываются, как правило, доменное имя, строка подключения к БД, recovery и прочая информация, которую хардкодить неприлично, а делать интерфейсы нецелесообразно (нужно раз в сто лет). Это текстовый файл, который можно изменить руками

Другой подход, который тоже практикуется нередко для подобных случаев - это компромисс - технологические вещи (оменное имя, строка подключения...) - в конфигфайле - это для профи, а вещи, которые потенциально переписываются неспециалистами в специальных get запросах, которые могут быть выполнены только людьми с определенными правами. Что-то типа адрес/setDiscontValue/0.8 - устанавливает коэффициент дисконта 0.8 и т.д - это позволяет обойтись без интерфейса. А хранятся все коэффициенты в одном json или xml в БД (лучше, как думаешь, почему?) или файле
