### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#4]
Рассмотрим аналоги музыкального интернет магазина. В качестве аналогов будут использоваться Мир музыки (https://mirm.ru/), DMTR Pedal shop (https://dmtrpedals.ru/), Skifmusic (https://skifmusic.ru/) 
Мир музыки
В нем реализованы услуги: поиск по названию, просмотра каталога товара (инструменты и оборудование подразделены на категории, также их можно отфильтровать по брендам), услуга заказа (оформление заказа происходит через Корзину, звонок оператору или написать письмо на почту магазина, с указанием товаров), предоставлены способы оплаты (наличная оплата, безналичный платёж, оплата банковской картой, электронные платежи), услуги доставки, акции и скидки. Также указаны услуги:  условия возврата и обмена (происходит вне онлайн магазина, в самом офисе), Сервисные центры (перечислены адреса, график работы, контакты), помощь покупателям (онлайн - консультации, написать на почту или звонок на горячую линию магазина). Для авторизации пользователя используется номер телефона, почта, Yandex ID. 
Просмотр товара: указаны цена, описание, характеристики объекта, оценки, добавление в корзину и недавно просмотренные товары ниже
Из отзывов в интернете: выбор инструментов удобный
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/716a2b52-fac2-4090-8804-bc0b88412bc8)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/6ed9c9c8-0e88-4333-a9dd-e74fed966a8a)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/d41ce7d2-ec7e-4722-86b0-f7d41de60761)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/326bad16-c876-4d30-874d-d666a776877e)
2. DMTR Pedal shop
В данной системе есть функции: просмотра каталога (указаны оборудование, инструменты, аксессуары идр), возможна фильтрация по цене, бренда,  назначения , типа питания, цвет, гарантии магазина и производителя, есть товары без фотографии. При просмотре товара есть цена, наличие , положить в корзину или предложить обмен, доставка, описание, характеристика, отзывы, доставка и оплата, рассрочка и кредит. 
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/36ade4a8-2b85-452d-b750-4ba1bfce2fd4)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/e35788cb-538e-483b-bcc4-a228deb129b1)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/44eff92c-b4db-43e2-82a9-ecbeb458129d)
Можно сортировать по состоянию (новый или б/у), наличии, по популярности / новизне / рейтингу итд
Оплата может производится наличными или оплатой картой (также покупка в кредит, покупка в рассрочку). Доступны доставка или самовывоз. Услуги обмен и выкуп заполняются в онлайн форму.
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/97770f84-ad15-4b30-bab2-e8e92d3e706a)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/59ccdecf-2f01-402f-9153-b20d61c77d36)
Аккаунт для пользователя - вход по телефону. Обратная связь: почта и телефоны. 
3. SKIFMUSIC
Функционал
Каталог: инструменты делятся на классы (ударные, клавишные итд) , а потом уже на разделы, где выводятся товары. Есть фильтрация. Товары можно добавлять в корзину. При просмотре товара есть информация. 
Возможен поиск товаров. 
Аккаунт - вход по почте и паролю. 
Обратная информация - задать вопрос онлайн, форма обратной связи, почта и звонок по телефону. 
Оплата заказа наличными при получении, картой на сайте, безналичный отчет, покупка в рассрочку. Есть возможность заказа оптом, тогда связь осуществляется по почте. Заказ оформляется самостоятельно или через оператора. 
Есть услуги ремонта, доставки и возврата. На ремонт и настройку можно оставить заявку , записав телефон для связи. Там же указан прайс - лист с отзывами. 
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/e3e16e40-dbda-4035-8461-88688e2a249c)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/b1dffa3d-19a1-46cf-8066-6c83d5c09f50)
![image](https://github.com/AnalitikBigData/MusicShop/assets/110247445/cb9260fd-d27a-4a61-8e5e-55ada56e222d)

**Comment by AnalitikBigData** [comment]
Сравнение Систем аналогов
<img width="592" alt="Снимок экрана 2023-09-20 в 00 36 13" src="https://github.com/AnalitikBigData/MusicShop/assets/110247445/e11d8089-d4ce-41b0-88b8-682c666ce419">
Наиболее универсальной является система SKIFMUSIC. 

P. S. : подумала лучше объединить функционал в таблицу.

**Comment by wldmr-key** [comment]
все хорошо

> подумала лучше объединить функционал в таблицу.

и, правильно!

Было бы неплохо составить резюме по тому, какой опыт ты берешь в разработку, от чего отказываешься, что делаешь по другому

**Comment by AnalitikBigData** [comment]
резюме. 
Исходя из проанализированных систем, для реализуемой системы будет реализован функционал: просмотр товаров по категориям, заказа онлайн и записи на услуги онлайн.  Фильтрация реализована не будет по популярности, по дате добавления товара в список, по алфавиту. В данной системе можно будет выбрать способ оплаты. В система будет обеспечена форма авторизации. В системах рассоренных выше пользователь мог создать свой личный кабинет через ФИО, телефона или войти через аккаунты Yandex / Google , в данной системе регистрация будет зависеть от имени и телефона или почты (по выбору). Обратная связь реализована не будет в системе.

**Comment by wldmr-key** [comment]
все супер. Нужно только вычитать текст, ты явно торопилась, когда писала ))
