### ISSUE TITLE
Создать концептуальную схему данных предметной области (предварительную, конечно)

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#5]
такая была концептуальная схема раньше
![_магазин_-Страница 1](https://github.com/AnalitikBigData/MusicShop/assets/110247445/b31b9edf-a3e3-403d-8a67-54d83512d3f1)

**Comment by AnalitikBigData** [comment]
Появился вопрос, пока рисовала скетч: стоит ли клиентов разделять на физических лиц и юридических (разные организации театры, муз школы, муз группы итд). Если клиента  не разделить физ и юр лиц получится антипаттерн EAV ?

**Comment by wldmr-key** [comment]
честно говоря, в такой реализации антипатерна еще нет. Фактически это кличка

Вот, если ты будешь оформлять договоры, то, да, стоит подумать

**Comment by AnalitikBigData** [comment]
добавила новые атрибуты : фото для инструментов (тк из скетча поняла, что у инструмента должна быть обложка - 1 фото), класс и тип инструмента (тк инструменты делятся на классы например, струнные, а потом на типы , например, арфа), логин и пароль для сотрудников и клиентов. Что ещё исправить?
![_магазин_ drawio](https://github.com/AnalitikBigData/MusicShop/assets/110247445/0ac1d960-aab5-4f8c-8778-b53e114ef635)

**Comment by wldmr-key** [comment]
я не догоняю - комиссионные инструменты у тебя, ведь, остались? Я правильно понимаю, что магазин выкупает инструмент и забывает о том, кто принес его на комиссию (неправильно выразился - не на комиссию, а продал)?

это вопрос, а не призыв к исправлениям. Схема выглядит норм

**Comment by AnalitikBigData** [comment]
Да, комиссионка осталась. На примере напишу: Обломов сдал в комиссионку рояль. Воланд принял у Обломова инструмент. (На этом заказ Обломова закончился, других услуг не было в заказе). Потом другой сотрудник Шариков продаёт рояль как б/у Мироновой. ( в заказе Мироновой значится, что сотрудник Шариков , услуга - продажа). Разве не так? Я с чем-то путаю?

**Comment by wldmr-key** [comment]
нет, все норм, кроме того, что мне эта цепочка не была очевидной после чтения описаний ))

**Comment by AnalitikBigData** [comment]
Возник вопрос: нужно вынести в новую сущность Роль из атрибута. (На схему добавлю Роль, тк должность ≠ роли). Как я думаю, одну роль могут иметь несколько сотрудников (админы несколько человек , обычные тоже несколько) ?

**Comment by wldmr-key** [comment]
не уверен, что нужна отдельная сущность, но, да, ты мыслишь правильно

**Comment by wldmr-key** [comment]
я забыл и не смог вычислить навскидку, что означает вторая связь склада с инструментом?

**Comment by AnalitikBigData** [comment]
я забыл и не смог вычислить навскидку, что означает вторая связь склада с инструментом? - инструмент отсутсвует на складе. (по крайней мере я так думаю) а это не так?

**Comment by wldmr-key** [comment]
> я забыл и не смог вычислить навскидку, что означает вторая связь склада с инструментом? - инструмент отсутсвует на складе. (по крайней мере я так думаю) а это не так?

)) Это не так. "Тьма - это отсутствие света". Если у инструмента нет связи со складом, то его там нет. Так что вторая связь не нужна. А та, что есть допускает отсутствие

**Comment by AnalitikBigData** [comment]
убрала связь
![_магазин_ drawio](https://github.com/AnalitikBigData/MusicShop/assets/110247445/57cb7b1e-dec2-4d77-84d4-86b56b5d78db)
