### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#6]
1. Главная страница
![IMG_5374](https://github.com/AnalitikBigData/MusicShop/assets/110247445/39972996-76b8-42eb-99df-1ca3d1d9a1a3)

2. Заводы
![IMG_5375](https://github.com/AnalitikBigData/MusicShop/assets/110247445/bf94bb67-cff1-46f9-b704-8c3c0364d297)

3. Авторизация для клиентов 
![IMG_5381](https://github.com/AnalitikBigData/MusicShop/assets/110247445/0c2639f3-9ef8-430e-9cf4-6024de17d480)

4. Каталог товаров
![IMG_5377](https://github.com/AnalitikBigData/MusicShop/assets/110247445/8d8b471b-ed96-43a6-84d1-74958070db7f)

5. Услуги и заказы

![IMG_5378](https://github.com/AnalitikBigData/MusicShop/assets/110247445/2b375c16-2d3e-411a-b641-0f4fa209401f)

6. Авторизация для сотрудников
![IMG_5379](https://github.com/AnalitikBigData/MusicShop/assets/110247445/6a911103-eaed-487a-b76d-7da24fae7631)

**Comment by AnalitikBigData** [comment]
![6CC5C4F8-3F7B-4776-89CA-23A5DCD96DF2](https://github.com/AnalitikBigData/MusicShop/assets/110247445/30c8f39e-21d4-4910-b637-6ca064030aef)
Вход 

2. создание нового сотрудника 
![7560A61A-2B30-4286-955C-5C83F3BA692A](https://github.com/AnalitikBigData/MusicShop/assets/110247445/05af8e04-67b2-4700-a457-cb0e32920d41)
Вносит в бд админ

3. форма для нового клиента 
![816C04AE-107B-42EA-8C83-38F3CC788ACF](https://github.com/AnalitikBigData/MusicShop/assets/110247445/13edfbe4-e458-492e-8258-388421b3a622)


P.S. Примерно исправлен на авторизацию.

**Comment by wldmr-key** [comment]
войти как сотрудник/войти как клиент выглядит неуклюже

Принято или делать разные endpoint/адреса для разных ролей. Или можно различать их по login
