### ISSUE TITLE
Реляционная модель

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#8]

**Comment by AnalitikBigData** [comment]
![_магазин_реляц drawio](https://github.com/AnalitikBigData/MusicShop/assets/110247445/59c96f60-498a-45ef-a9fc-0c8c5efa7438)

P. S. строки заказа - в ней все FK образуют PK? кажется, что для строки заказа не нужен id как PK

**Comment by wldmr-key** [comment]
> строки заказа - в ней все FK образуют PK? кажется, что для строки заказа не нужен id как PK

абсолютно верно. Но в нотации PK всегда отмечают

PK FK1
PK FK2
PK FK3
PK FK4

означает, что первичный ключ - составной над 4 атрибутами
