### ISSUE TITLE
Обоснование выбора БД 

### ISSUE THREAD

**Issue by AnalitikBigData** [AnalitikBigData/MusicShop#9]

**Comment by AnalitikBigData** [comment]
Для разработки данной системы будут применены технологии PostgreSQL и ASP. Net. 
PostgreSQL базируется на языке SQL и поддерживает многочисленные возможности. Преимущества PostgreSQL: 
1. можно установить на любой ОС. 
2. множество возможностей для пользователей.  Например, можно выбрать такие функции, как восстановление на момент времени, упреждающее ведение журнала, элементы детализированного управления доступом, табличные пространства, вложенные транзакции, оперативное резервное копирование и многовариантное управление параллелизмом
3. Надежность и соответствие требованиям. Cоответствует свойствам атомарности, согласованности, изолированности и долговечности (ACID) для транзакций баз данных
4. Гибкость. База данных PostgreSQL совместима с целым рядом важнейших языков программирования и протоколов, включая C, C++, Go, Perl, Python, Java, .Net, Ruby, ODBC и Tcl. Это означает, что пользователи смогут работать на том языке, который они знают лучше, без риска возникновения системных конфликтов.
пользователи могут получать доступ к данным JSON с помощью выражений пути SQL и JSON.
5. Поддержка множества типов данных. Еще одна особенность PostgreSQL — поддержка большого количества типов записи информации. Это не только стандартные целочисленные значения, числа с плавающей точкой, строки и булевы значения, но и денежный, геометрический, перечисляемый, бинарный и другие типы. В ней есть поддержка XML, JSON и NoSQL-баз. 
Недостатки: Повышенное потребление ресурсов. В сравнении с некоторыми другими СУБД, PostgreSQL может потреблять больше ресурсов (включая оперативную память и процессорное время). Это особенно заметно при работе с большими объёмами данных и выполнении сложных запросов.

PostgreSQL используют 1. Бэкенд-разработчики, которым приходится взаимодействовать с базами данных при работе с «серверной» частью сайта. 2. Администраторы и разработчики баз данных — специалисты, основная задача которых заключается в обслуживании и поддержке работоспособности базы. 3. DevOps-инженеры, обслуживающие рабочую инфраструктуру проекта.
В совремменном мире многие компании используют возможности PostgreSQL, например, такие  как Sony, Huawei, Alibaba, Instagram, Tripadvisor, Hitachi, Яндекс, Skype, Reddit, Amazon Redshift, FlightAware. 
Рассмотрим ASP. Net. 
ASP.NET (Active Server Pages для .NET) — платформа разработки веб-приложений, в состав которой входят: веб-сервисы, программная инфраструктура, модель программирования, от компании Майкрософт. 
ASP.NET входит в состав платформы .NET Framework и является развитием более старой технологии Microsoft ASP. ASP.NET представляет технологию для создания веб-приложений на платформе .NET, развиваемую компанией Microsoft. В качестве языков программирования для разработки приложений на ASP.NET Core используются C# и F#.
ASP.NET предоставляет следующие преимущества:
1) Единое решение для создания пользовательского веб-интерфейса и веб-API.
2) позволяет использовать в браузере язык C# вместе с JavaScript. совместное использование серверной и клиентской логик приложений, написанных с помощью .NET;
3) Возможность разработки и запуска в ОС Windows, macOS и Linux.
4) Многофункциональность. ASP.NET обладает широким набором различных функций, компонентов, элементов управления, шаблонов страниц и т.д. Благодаря этому с помощью фреймворка можно разрабатывать сайты и веб-приложения различного размера и структуры, придавать им уникальный облик, тестировать готовые продукты и выполнять подавляющее большинство операций, связанных с разработкой. Кроме того, функционал платформы можно расширить путем установки дополнительных расширений и интеграции с .NET.Framework.
5) Благодаря модульности фреймворка все необходимые компоненты веб-приложения могут загружаться как отдельные модули через пакетный менеджер Nuget.
6) Поддержка работы с большинством распространенных систем баз данных: MS SQL Server, MySQL, Postgres, MongoDB
Недостатки ASP.NET следующие: Разработка на ASP.NET довольно дорогостоящая. На стоимость влияет лицензирование инструментов, которые используются, а также подбор специалистов, разработчиков, применяющих данную технологию для создания бизнес-продуктов.
На данный момент компании используют ASP.Net. Например, Roblox, MasterCard, Microsoft применяют технологии для создания своих решений. 
ASP.NET — это фреймворк для языков из семейства .NET, который позволяет писать серверную часть сайтов. С его помощью созданы такие площадки, как: Exchanger.com; MSN.com; Microsoft.com; Dell.com; Stackoverflow.com

**Comment by wldmr-key** [comment]
пойдет. Убери будущее время
